Validating inputs and switching to using dotenv for defaults and overrides

diff --git a/.github/actions/visual-regression-tests/action.yml b/.github/actions/visual-regression-tests/action.yml
--- a/.github/actions/visual-regression-tests/action.yml
+++ b/.github/actions/visual-regression-tests/action.yml
@@ -1,40 +1,29 @@
 name: 'CI-Pocketknife visual regression action'
 description: 'It allows running visual regression tests as actions'
-inputs:
-  ci_vr_reference_website_url:
-    description: 'Reference URL'
-    required: true
-  ci_vr_test_website_url:
-    description: 'Test URL'
-    required: true
-  ci_vr_url_list_limit:
-    description: 'Limit URLs list'
-    required: false
-    default: 20
-  ci_vr_url_list_randomize:
-    description: 'Randomize URLs list'
-    required: false
-    default: false
-  ci_vr_working_folder:
-    description: 'Working folder on host'
-    required: false
-    default: /tmp/ci
-  ci_vr_docker_network:
-    description: 'Network switch for dockery'
-    required: false
-    default: host
 runs:
   using: "composite"
   steps:
-    - name: Set up environment variables
+    - name: Read dotenv defaults file for visual regression tests
+      uses: c-py/action-dotenv-to-setenv@v2
+      with:
+        env-file: ./.github/actions/visual-regression-tests/defaults.env.visreg
+
+    - name: Read dotenv file for visual regression tests
+      uses: c-py/action-dotenv-to-setenv@v2
+      with:
+        env-file: .env.visreg
+
+    - name: Validate environment variables
       shell: bash
       run: |
-        echo "CI_VR_WORKING_FOLDER=${{ inputs.ci_vr_working_folder }}" >> $GITHUB_ENV && \
-        echo "CI_VR_REFERENCE_WEBSITE_URL=${{ inputs.ci_vr_reference_website_url }}" >> $GITHUB_ENV && \
-        echo "CI_VR_URL_LIST_LIMIT=${{ inputs.ci_vr_url_list_limit > 0 && '--limit ' || '' }}${{ inputs.ci_vr_url_list_limit > 0 && inputs.ci_vr_url_list_limit || '' }}" >> $GITHUB_ENV && \
-        echo "CI_VR_URL_LIST_RANDOMIZE=${{ inputs.ci_vr_url_list_randomize && inputs.ci_vr_url_list_randomize != 'false' && '--random' || '' }}" >> $GITHUB_ENV && \
-        echo "CI_VR_TEST_WEBSITE_URL=${{ inputs.ci_vr_test_website_url }}" >> $GITHUB_ENV && \
-        echo "CI_VR_DOCKER_NETWORK=${{ inputs.ci_vr_docker_network }}" >> $GITHUB_ENV
+        [[ "${{ env.CI_VR_REFERENCE_WEBSITE_URL }}" ]] || { echo "CI_VR_REFERENCE_WEBSITE_URL input is required" ; exit 1; }
+        [[ "${{ env.CI_VR_TEST_WEBSITE_URL }}" ]] || { echo "CI_VR_TEST_WEBSITE_URL input is required" ; exit 1; }
+
+    - name: Massage environment variables
+      shell: bash
+      run: |
+        echo "CI_VR_URL_LIST_LIMIT=${{ env.CI_VR_URL_LIST_LIMIT > 0 && '--limit ' || '' }}${{ env.CI_VR_URL_LIST_LIMIT > 0 && env.CI_VR_URL_LIST_LIMIT || '' }}" >> $GITHUB_ENV && \
+        echo "CI_VR_URL_LIST_RANDOMIZE=${{ env.CI_VR_URL_LIST_RANDOMIZE && env.CI_VR_URL_LIST_RANDOMIZE != 'false' && '--random' || '' }}"  >> $GITHUB_ENV
 
     - name: Install automated testing tools
       shell: bash
